application: post-bot
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /_ah/mail/.+
  script: src/main.py
  login: admin
  
- url: /bot
  script: src/postbot.py
  
- url: /.*
  script: src/main.py
  
inbound_services:
- xmpp_message
- mail
